version: 2
updates:
- package-ecosystem: npm
  directory: "/src"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.5
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.3
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
    - 5.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: postcss-loader
    versions:
    - 5.1.0
