title = "Steve Bargelt"
baseURL = "https://www.bargelt.com"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-31323933-1"
enableRobotsTXT = true

# Highlighting config (Pygments)
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
# pygmentsUseClasses = true
pygmentsUseClassic = true

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Steve Bargelt"
  facebook = ""
  twitter = "https://twitter.com/stevebargelt"
  instagram = ""
  youtube = "https://www.youtube.com/stevebargelt"
  github = "https://github.com/stevebargelt"
  linkedin = "https://linkedin.com/in/stevebargelt"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/PikePlace.jpg"
