backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: 'static/assets/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/assets/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'post' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/post' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Categories', name: 'categories', widget: 'list'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string'}
      - { label: 'Featured Image', name: 'featured_image', widget: 'image' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'post' }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
      - { label: 'Body', name: 'body', widget: 'markdown' }
